# Generated by Django 5.0.1 on 2024-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Active', models.CharField(max_length=1)),
                ('URL', models.CharField(max_length=500)),
                ('APIKey', models.CharField(max_length=100)),
            ],
        ),
    ]
